### ISSUE TITLE
[Menu] Deleting nonexisting saves causes game to enter undefined state

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#13]
Deleting nonexisting saves causes game to enter undefined state

Steps to reproduce:
 - launch game
 - select load game (at this point there are no saved games available, related to #6 )
 - click delete save
 - game goes into an undefined state:
![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/c294e309-3fa9-4470-9e3a-1d5202c46d8c)

**Comment by MaciejWorwa** [comment]
I fixed that. I was because it didn't check for empty dropdown value before trying to load file.
