### ISSUE TITLE
[Game environment] Scaling does not work as expected

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#14]
Content of the menu does not scale in windowed mode

Steps to reproduce:
- select "Sterowanie" from main menu
- go into window mode
- make the window smaller

![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/1a53e66a-a2cc-4de7-9d18-22878268dcb8)

**Comment by MaciejWorwa** [comment]
For now application force fullscreen mode during launching. I still looking for best solution to scaling game window proportionally

**Comment by MaciejWorwa** [comment]
Fixed.
