### ISSUE TITLE
[Map creator] Collider behaviour between controls and map

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#15]
The slider for map size has a big circle, if I click it with map beneath it, it creates a wall tile (compare images)

![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/a2d13c5e-e38b-45df-a172-dc107968d8b8)
![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/e2f731f8-c97f-478c-8458-f5ed9033a927)

Is this expected behaviour? Or would we rather split the scene into 2 sections: one for controls and one for map?

**Comment by MaciejWorwa** [comment]
Fixed.
