### ISSUE TITLE
[Battleground] No information is displayed for user if he can't cast spells when too far away

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#18]
- Created an elf
- Increased his Magic to 1
- Couldn't cast spells, because my character was too far away? This is counter-intuitive

After a while, the "run" and "walk" buttons stopped working :(

![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/45c5ad7b-f967-46a0-99da-ad92bae0ab73)

**Comment by MaciejWorwa** [comment]
The reason is different. Just above the battlefield there is an invisible GUI object (text frame). Already fixed.
