### ISSUE TITLE
[Game environment] Window size/mode during launch

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#5]
Original statement: "Game opens by default on my secondary screen. The default behaviour should be so that it opens on the main screen. *//nie zauważyłem tego problemu*"

Current behaviour: game launches in the same state as when it was last closed. Important! The game creates some temporary files to preserve the state! 
 - I removed the git repo
 - I cloned a fresh version
 - Game launched in the same size window as before

If you:
- open the game, put it in window mode
- change size
- restart the game
- game launches with last selected size

Where is the configuration saved?

**Comment by MaciejWorwa** [comment]
ChatGPT answer:

"In Unity, the configuration for the window size and mode is typically stored in the player settings file of your Unity project. When you change the size of the game window while running in windowed mode, Unity remembers that size and uses it as the default when the game is restarted.

The player settings file is an XML file with the extension .plist on macOS or .xml on Windows. Its exact location within your project depends on the platform you are building for:

For PC: The player settings file is located at <YourProject>/Build/WindowsPlayer/<YourProjectName>.exe.config.

For Mac: The player settings file is located at <YourProject>/Build/Mac/<YourProjectName>.app/Contents/Resources/Data/StreamingAssets/UnitySettings.plist.

Within the player settings file, you can find the configuration for the screen width, height, and whether the game should run in windowed or fullscreen mode. Unity updates these settings based on the last known configuration when the game is closed.

Note that the location and format of the player settings file can vary depending on the Unity version and the specific platform you are targeting. It's always a good idea to check the Unity documentation or the relevant platform-specific documentation for the accurate file location and format."

**Comment by MaciejWorwa** [comment]
I set fullscreen mode as default and allow application to run in background

**Comment by emcezet** [comment]
please dont reply with gpt content and either find out for yourself or use the docs
