### ISSUE TITLE
[Game environment] Saved maps are not available

### ISSUE THREAD

**Issue by emcezet** [MaciejWorwa/Warhammer_2.0#6]
- Saved maps didn't download with latest games *//nie zauważyłem tego problemu*

Still no saved maps when I launch the game
![obraz](https://github.com/MaciejWorwa/Warhammer_2.0/assets/33034962/2a8b746a-3ec7-4b87-9e84-f4a2977e8bb5)

**Comment by MaciejWorwa** [comment]
This is the path to find your saved files:

![image](https://github.com/MaciejWorwa/Warhammer_2.0/assets/115475673/51463b57-0c16-48a7-b131-7d3930fec0db)

I changed it couple of times last month, so maybe game doesn't see yout folder. You have to rename folder to Warhammer_2ed.

**Comment by emcezet** [comment]
My ask is for you to ship saved maps. Files in local data are not part of the repository.

**Comment by MaciejWorwa** [comment]
I added 3 example maps: forest, river and city. Player can choose one of them after click "Nowa gra" button. Maps are saved into game assets. Path: Warhammer_2.0/Warhammer_2ed_Data/Resources
